spring:
  datasource:
    url: ${DB_URL}
    username: ADMIN
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
   

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

