spring:
  datasource:
    url: ${DB_URL}
    username: ADMIN
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: BeautiClickHikariPool
      register-mbeans: true  
   

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        
         
        
jwt:
   secret: ${JWT_SECRET}
   expiration-ms: 86400000   # 24 hours

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs